---
version: '3.8'
services: 
   mydb: 
      image: postgres
      environment: 
         POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
         POSTGRES_USER_FILE: /run/secrets/pg_user
         POSTGRES_DB_FILE: /run/secrets/pg_db
      secrets: 
         - pg_password
         - pg_user
         - pg_db
      deploy: 
         replicas: 3
   myadminer: 
      image: adminer
      ports: 
         - 8080:8080
      deploy: 
         replicas: 3
secrets: 
  pg_password:
    external: true
  pg_user: 
    external: true
  pg_db: 
    external: true
...
