---
version: '3.8'
services:
   mydb: 
      image: mysql:5
      environment: 
           MYSQL_ROOT_PASSWORD: mvbrothers
      deploy: 
         replicas: 2
   mywordpress:
      image: wordpress
      ports:
         - 8989:80
      deploy: 
         replicas: 3
...

