---
version: '3.8'
services: 
   myjenkins: 
      image: jenkins/jenkins
      ports: 
         - 5050:8080
      deploy: 
         replicas: 2
         placement: 
           constraints: 
             - node.hostname == manager
   qaserver: 
      image: tomcat
      ports: 
         - 6060:8080
      deploy: 
         replicas: 3
         placement: 
           constraints: 
             - node.hostname == worker1
   prodserver: 
      image: tomcat
      ports: 
         - 7070:8080
      deploy: 
         replicas: 4
         placement: 
           constraints: 
             - node.hostname == worker2
...
